### ISSUE TITLE
Crash: Whenever I use "Pain Buckler" (Wave tier 1 guard art), game immediately crashes

### ISSUE THREAD

**Issue by Alignn** [XenonA7/xenons-triblader-mod#8]
![20220729131953_1](https://user-images.githubusercontent.com/18351802/181756771-481be872-5389-453d-9afc-0b72c98a3774.jpg)
![20220729141549_1](https://user-images.githubusercontent.com/18351802/181756775-b16f4b43-5621-4b95-b027-b6cbd58cdf6a.jpg)
This being after getting both elements in Gaia's Garden. Tried three times with the same result, one of them outside of combat.

**Comment by XenonA7** [comment]
Looking at the code, I think this issue might be on controller only (as opposed to keyboard/mouse). What input device are you using?

**Comment by XenonA7** [comment]
I also need to know if this crash happens when using a parry art such as "Recoil Slash" (Heat guard lv. 1). The action step causing the crash with Pain Buckler is called **WAIT_WHILE_AIMING**, which is a modified version of **WAIT_UNTIL_GUARDED**. Recoil Slash uses WAIT_UNTIL_GUARDED. These action steps contain the following code which is causing the error, and it appears that it only happens when using a controller.

![image](https://user-images.githubusercontent.com/105614278/181871566-df3d73f7-1fcc-4f5b-8659-0eb138657890.png)

**Comment by Alignn** [comment]
That fits then, I am indeed using a controller, and it doesn't happen with Recoil Slash or any other guard arts I've unlocked so far (which is T1&T2 for all elements).

**Comment by XenonA7** [comment]
This should be addressed in version 0.1.3. Please verify and close the issue if Pain Buckler works.

**Comment by Alignn** [comment]
Tested and had no issues! Closing as asked.
